# Generated by Django 5.0.3 on 2024-03-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_entry_score_num_entry_scores_alter_bloger_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('description', models.TextField(max_length=128)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatEntryMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='ChatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('scores', models.BigIntegerField(null=True)),
                ('score_num', models.IntegerField(null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatentrymeta')),
            ],
        ),
    ]
