# Generated by Django 5.0.3 on 2024-03-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_score_num_entry_scores_alter_bloger_birth_date_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatentry',
            name='metadata',
        ),
        migrations.AddField(
            model_name='chatentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bloger'),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatentry')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatEntryMeta',
        ),
    ]
