# Generated by Django 5.0.3 on 2024-06-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='Chat',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chat',
        ),
    ]
