# Generated by Django 5.0.3 on 2024-03-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatentry_metadata_chatentry_owner_citation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatentry',
            name='owner',
        ),
        migrations.AddField(
            model_name='chatentry',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatentry',
            name='score_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatentry',
            name='scores',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
