# Generated by Django 5.0.3 on 2024-03-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_score_num_entry_scores_alter_bloger_birth_date_and_more'),
        ('chat', '0003_remove_chatentry_owner_chatentry_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bloger'),
        ),
    ]
