# Generated by Django 5.0.3 on 2024-03-28 10:48

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='date_added',
        ),
        migrations.AddField(
            model_name='topic',
            name='permision',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Group'), (2, 'For All')], default=0),
        ),
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('birth_date', models.DateField(blank=True)),
                ('phone_number', models.CharField(max_length=12, validators=[blog.models.is_phone_number])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger'),
        ),
        migrations.CreateModel(
            name='UserGroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
    ]
