# Generated by Django 5.0.3 on 2024-04-02 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='membership',
            field=models.ManyToManyField(related_name='friend_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
