# Generated by Django 5.0.3 on 2024-03-28 12:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_banner_group_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='score_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='scores',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[blog.models.is_phone_number]),
        ),
    ]
