# Generated by Django 5.0.3 on 2024-03-30 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_entry_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserGroupPreference',
        ),
    ]
