# Generated by Django 5.0.3 on 2024-03-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_description_group_name_group_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='user',
        ),
    ]
