# Generated by Django 5.0.3 on 2024-04-04 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_friendrequest_user_friendrequest_recepient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='recepient',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='recepients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
