# Generated by Django 5.0.3 on 2024-06-16 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_group_membership_remove_group_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='permision',
            new_name='permission',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
